
# Plugin Information
name: SimpleCore
author: vRqzor
main: vRqzor\SimpleCore\Main

# Versions
version: 1.0.0
api: 3.0.0

# Commands
commands:
 feed:
  description: Feed yourself!
  usage: Incorrect Usage!\nUsage: /feed
  permission: feed.command
  
# Permissions
permissions:
 feed.command
  default: true
